### ISSUE TITLE
New version only seems to work when minionconfig environment is set

### ISSUE THREAD

**Issue by claudekenni** [wcannon/salt-check#1]
When I set the environment, it works. 

```
lab08ld250:~ # grep ^#environment /etc/salt/minion
#environment: base

salt lab08ld250 saltcheck.run_state_tests sssd
lab08ld250:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1600, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/saltcheck.py", line 139, in run_state_tests
        paths = scheck.get_state_search_path_list()
      File "/var/cache/salt/minion/extmods/modules/saltcheck.py", line 631, in get_state_search_path_list
        environment = __opts__['environment']
    KeyError: 'environment'
```
```
lab08ld250:~ # salt --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.4
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.73-5-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64
```

**Comment by claudekenni** [comment]
Changing the line 631

```        environment = __opts__['environment'] ```
to
```        environment = __opts__.get('environment', '') ```
works.

**Comment by wcannon** [comment]
Thanks!  Just committed the fix directly.  Please give it a test or two.
