### ISSUE TITLE
saltcheck assumes base environment

### ISSUE THREAD

**Issue by mchugh19** [wcannon/salt-check#13]
When a minion uses a non-default environment like`environment: dev` saltcheck doesn't notice. 

```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1466, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/var/cache/salt/minion/extmods/modules/saltcheck.py", line 165, in run_highstate_tests
        sls_list = _get_top_states()
      File "/var/cache/salt/minion/extmods/modules/saltcheck.py", line 237, in _get_top_states
        for i in returned['base']:
    KeyError: 'base'
```

**Comment by wcannon** [comment]
Yes.  This was a design choice to only support the 'base' environment.  Do you think we should support the same environment lookup options as in salt highstate evaluations?  And, what percentage of companies would you estimate need this?

My concern with putting this in place is that it might add confusion, and it might not be needed by many companies. 

But, as always I'm open to suggestions / solutions.

**Comment by mchugh19** [comment]
Our usecase is to tie into our CI pipeline. With a team of people updating saltstates, we need to ensure they are tested before hitting the master branch which goes out to production. So we'd like to run lint and saltcheck tests before that merge to master. Right now that means that we merge into a development branch, Jenkins kicks off the lint, highstate, and saltcheck tests, and then we have the results to alert the human on if this passes the first hurdle to be merged into master. 

Thus, it would be nice if the run_highstate_tests was environmentally aware of this development branch.

It appears that the environment is queryable from the __opts__ variable if available. 
```
saltenv = kwargs.get('saltenv', None)
If saltenv is None:
        if __opts__.get('environment', None):
            saltenv =  __opts__['environment']
        else:
            saltenv = 'base'
```

**Comment by wcannon** [comment]
I'm going to start working on adding support for environments.  It's a little more complicated than it sounds because an environment can also include multiple paths for its search list.  Technically, this also applies to the "base" environment as well.

e.g.
```
dev:
   /path/one
   /path/two
   /path/three
```

**Comment by MAHDTech** [comment]
+1

Would love to see this.

Using GitLab CI, based on the Git branch this sets the environment, and I would like to run tests for the specific branch/environment rather than base each time.

**Comment by wcannon** [comment]
This issue is definitely overdue.  

I would also like to see this in the code.  But, I only operate in one salt environment.  So, I'm somewhat uncertain about how to test this easily.  @mchugh19  would you be willing to add this ability and data to test it?  I'd be happy to merge it in.
